package my.noveldoksuha.coreui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.luminance

@Composable
fun ColorScheme.isLightTheme() = background.luminance() > 0.5

val light_colorScheme = ColorScheme(
    primary = Grey25,
    onPrimary = Grey900,
    primaryContainer = Grey50,
    onPrimaryContainer = Grey800,
    inversePrimary = Grey900,
    secondary = Grey25,
    onSecondary = Grey900,
    secondaryContainer = ColorAccent,
    onSecondaryContainer = Grey25,
    tertiary = Grey200,
    onTertiary = Grey600,
    tertiaryContainer = Grey50,
    onTertiaryContainer = Grey900,
    background = Grey25,
    onBackground = Grey900,
    surface = Grey25,
    onSurface = Grey900,
    surfaceVariant = Grey50,
    onSurfaceVariant = Grey900,
    surfaceTint = Grey300,
    inverseSurface = Grey900,
    inverseOnSurface = Grey25,
    error = Error300,
    onError = Grey900,
    errorContainer = Error200,
    onErrorContainer = Grey800,
    outline = Grey800,
    outlineVariant = Grey200,
    scrim = Grey300,
)

val dark_colorScheme = ColorScheme(
    primary = Grey900,
    onPrimary = Grey25,
    primaryContainer = Grey800,
    onPrimaryContainer = Grey50,
    inversePrimary = Grey25,
    secondary = Grey900,
    onSecondary = Grey25,
    secondaryContainer = ColorAccent,
    onSecondaryContainer = Grey75,
    tertiary = Grey700,
    onTertiary = Grey300,
    tertiaryContainer = Grey600,
    onTertiaryContainer = Grey50,
    background = Grey900,
    onBackground = Grey50,
    surface = Grey900,
    onSurface = Grey25,
    surfaceVariant = Grey900,
    onSurfaceVariant = Grey50,
    surfaceTint = Grey700,
    inverseSurface = Grey25,
    inverseOnSurface = Grey900,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = Grey25,
    outlineVariant = Grey700,
    scrim = Grey800,
)

val black_colorScheme = ColorScheme(
    primary = Grey1000,
    onPrimary = Grey25,
    primaryContainer = Grey900,
    onPrimaryContainer = Grey100,
    inversePrimary = Grey25,
    secondary = Grey1000,
    onSecondary = Grey25,
    secondaryContainer = ColorAccent,
    onSecondaryContainer = Grey75,
    tertiary = Grey800,
    onTertiary = Grey300,
    tertiaryContainer = Grey700,
    onTertiaryContainer = Grey50,
    background = Grey1000,
    onBackground = Grey50,
    surface = Grey1000,
    onSurface = Grey25,
    surfaceVariant = Grey1000,
    onSurfaceVariant = Grey50,
    surfaceTint = Grey800,
    inverseSurface = Grey25,
    inverseOnSurface = Grey1000,
    error = Error600,
    onError = Grey25,
    errorContainer = Error800,
    onErrorContainer = Grey50,
    outline = Grey25,
    outlineVariant = Grey800,
    scrim = Grey900,
)

val midnight_colorScheme = ColorScheme(
    primary = Slate900,
    onPrimary = Slate100,
    primaryContainer = Slate800,
    onPrimaryContainer = Slate100,
    inversePrimary = Slate100,
    secondary = Slate900,
    onSecondary = Slate100,
    secondaryContainer = Sky400,
    onSecondaryContainer = Slate100,
    tertiary = Slate700,
    onTertiary = Slate100,
    tertiaryContainer = Slate800,
    onTertiaryContainer = Slate100,
    background = Slate900,
    onBackground = Slate100,
    surface = Slate900,
    onSurface = Slate100,
    surfaceVariant = Slate900,
    onSurfaceVariant = Slate100,
    surfaceTint = Slate800,
    inverseSurface = Slate100,
    inverseOnSurface = Slate900,
    error = Error600,
    onError = Slate100,
    errorContainer = Error800,
    onErrorContainer = Slate100,
    outline = Slate100,
    outlineVariant = Slate700,
    scrim = Slate900,
)

val lava_colorScheme = ColorScheme(
    primary = Zinc900,
    onPrimary = Zinc100,
    primaryContainer = Zinc800,
    onPrimaryContainer = Zinc100,
    inversePrimary = Zinc100,
    secondary = Zinc900,
    onSecondary = Zinc100,
    secondaryContainer = Red500,
    onSecondaryContainer = Zinc100,
    tertiary = Zinc700,
    onTertiary = Zinc100,
    tertiaryContainer = Zinc800,
    onTertiaryContainer = Zinc100,
    background = Zinc900,
    onBackground = Zinc100,
    surface = Zinc900,
    onSurface = Zinc100,
    surfaceVariant = Zinc900,
    onSurfaceVariant = Zinc100,
    surfaceTint = Zinc800,
    inverseSurface = Zinc100,
    inverseOnSurface = Zinc900,
    error = Error600,
    onError = Zinc100,
    errorContainer = Error800,
    onErrorContainer = Zinc100,
    outline = Zinc100,
    outlineVariant = Zinc700,
    scrim = Zinc900,
)
